# Generated by Django 3.1 on 2021-03-03 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
