# Generated by Django 3.1 on 2021-03-05 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0008_auto_20210304_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
